baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'AI Prompts'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "light"
  ShowBrandLogo = true
  logo = "logo.png"


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
